infrastructure/booksite/intro.md
Here's a first attempt to fill in the intro to the book and the landing page. I've brought things over from the initial proposal and rewritten them a bit. To be honest, I think it should have a bit more of structure and maybe flow a bit better, but I thought I'd push this first to kick the tires. 
What do you think @sjsrey / @ljwolf ? Feel free to either suggest edits under a code review, or to push directly modifications to my branch.
=> First attempt to intro text

notebooks/10_clustering_and_regionalization.ipynb, notebooks/10_clustering_and_regionalization.md
This addresses questions raised in #19. 
We'll have to chat & see if the meanings changed when I reinterpreted the question intent.
=> answer questions about clustering questions

notebooks/08_point_pattern_analysis.md
This is a re-submission of #88, correctly rebased on master. it updates the point patterns chapter with additional revisions for the new release of `pointpats`.
=> update point patterns for new pointpats api

Dockerfile, data/airbnb/regression_cleaning.ipynb, data/countries/countries_cleaning.ipynb, data/h3_grid/build_sd_h3_grid.ipynb, data/nasadem/build_nasadem_sd.ipynb, data/tokyo/tokyo_cleaning.ipynb
Merging as this is a little fix for issues that appeared with #98
=> Fix data downloads and update gds_env for Binder backend

notebooks/12_feature_engineering.md, notebooks/references.bib
=> Review of Spatial Feature Engineering

notebooks/09_spatial_inequality.md
=> Formatting issues in 09

notebooks/09_spatial_inequality.ipynb, notebooks/09_spatial_inequality.md, notebooks/references.bib
=> Inequality revision

notebooks/06_spatial_autocorrelation.ipynb, notebooks/06_spatial_autocorrelation.md
Fixing small typo that was emailed to Dani. Issue described [here](https://github.com/gdsbook/book/issues/121).
I am using a slightly updated version of python (3.8.3), and this is recorded in [line 1383](https://github.com/jeffcsauer/book/commit/dfcc85bc9a567a3628deab68e787f632efaba0e6#diff-a6158c658d2d5126d3bbfd2ac0884e33eb8f94dd6afdde64dd97379f61f55af2L1381). Not sure if that will cause an issue..
=> Fixing small typo. Resolves: #121

Makefile, infrastructure/website_content/_static/custom.css
This addresses #147 
I think the change is not too much "in your face" but I'd vote to go for it, it feels elegant.
=> Add Computer Modern sans serif as main font

notebooks/04_spatial_weights.ipynb, notebooks/04_spatial_weights.md
I think there were other mistakes before chapter 4, but I didn't start noting them down until after I emailed @darribas.
=> suggesting typo fixes for chapter 4

Makefile, notebooks/02_geospatial_computational_environment.md, notebooks/references.bib
This PR implements #170 and is the first final pass over Ch.2. From here, @sjsrey and @ljwolf need to do their own final passes.
=> Ch2 fpass dab

notebooks/06_spatial_autocorrelation.ipynb, notebooks/06_spatial_autocorrelation.md
I've addressed the last comment in #32 here, which I failed to do in #179
=> fix standardization in the moran scatterplot

Makefile, notebooks/09_spatial_inequality.ipynb
Our nb and md were out of sync for 09.
Also updated Makefile to run container locally
=> sync 09 nb and update Makefile

notebooks/09_spatial_inequality.ipynb, notebooks/09_spatial_inequality.md, notebooks/references.bib
=> ch09 final edits

notebooks/03_spatial_data.ipynb, notebooks/03_spatial_data.md
There was bad meta data in this cell and it broke the build.
=> fix broken caption for Sao Paulo

notebooks/01_geo_thinking.ipynb, notebooks/01_geo_thinking.md, notebooks/07_local_autocorrelation.ipynb, notebooks/07_local_autocorrelation.md, notebooks/10_clustering_and_regionalization.ipynb, notebooks/10_clustering_and_regionalization.md, notebooks/12_feature_engineering.ipynb, notebooks/12_feature_engineering.md
This adds reading for all of the remaining chapters except those @sjsrey is doing (05, 06, 09). 
This should just touch four md/ipynb pairs!
=> Reading for 01, 07, 10, and 12. 

notebooks/09_spatial_inequality.ipynb, notebooks/09_spatial_inequality.md, notebooks/references.bib
=> Next steps for 09

notebooks/09_spatial_inequality.ipynb
The 09 nb is missing the change for the correct cite.
=> update cite 

LICENSE, README.md, infrastructure/website_content/intro.md
=> Move to new title accross

infrastructure/ga_environment.yml, infrastructure/website_content/_toc.yml, notebooks/00_toc.md, notebooks/01_geo_thinking.md, notebooks/02_geospatial_computational_environment.md, notebooks/05_choropleth.md, notebooks/06_spatial_autocorrelation.md, notebooks/07_local_autocorrelation.ipynb, notebooks/07_local_autocorrelation.md, notebooks/08_point_pattern_analysis.md, notebooks/10_clustering_and_regionalization.md, notebooks/11_regression.md, notebooks/12_feature_engineering.md, notebooks/references.bib, notebooks/references.md
More fixes, this should make the HTML build...
=> Testfails2

notebooks/07_local_autocorrelation.ipynb, notebooks/07_local_autocorrelation.md
This fixes#251 and should be ready to merge, I don't think it conflicts with other PRs open in parallel
=> Replace  by  as per @pareyesv suggestion in #251

Dockerfile, Makefile, notebooks/02_geospatial_computational_environment.md
=> Upgrade book to gds_env:7.0 from 6.1

notebooks/04_spatial_weights.ipynb, notebooks/04_spatial_weights.md, notebooks/09_spatial_inequality.ipynb, notebooks/09_spatial_inequality.md, notebooks/10_clustering_and_regionalization.ipynb, notebooks/10_clustering_and_regionalization.md, notebooks/11_regression.ipynb, notebooks/11_regression.md, notebooks/12_feature_engineering.ipynb, notebooks/12_feature_engineering.md
There are also a couple of updates on the kernel name but can be ignored.
=> Minor amendments to chapter cross-links. Fixes #215

notebooks/prologue.md
addresses #252 (prologue only)
=> [WIP] Prologue

infrastructure/publisher/Back-copy.md, infrastructure/publisher/Makefile, infrastructure/publisher/abstracts.md, infrastructure/publisher/abstracts.py
=> Draft of Back Copy text

infrastructure/website_content/_config.yml
This updates the analytics tracker code for google's new G4A system.
=> update GA tracker

.github/workflows/test_book.yml, infrastructure/book_stack.yml
This is a yaml file to setup local testing for continuous integration on the book.
=> Add yaml file to setup nightly testing infrastructure

notebooks/03_spatial_data.md, notebooks/07_local_autocorrelation.md
Addressing #311. This is re-running the chapters but, for ch.7, also adapting code to make it run on latest versions of `xarray`/`pysal`. Ready to merge.
=> Re-render of ch. 3 and 7, including adapting W raster example in 7
